In [1]:
### 第11章 表关联,vlookup
### pd.merge(df_main,df_city,on = "id")  pd.concat([df_main,df_main])

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, date, time, timedelta
from pandas.tseries.offsets import Day,Hour,Minute

import sys
stdo = sys.stdout
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stdout= stdo

In [3]:
### 加载join需要的 主表 和 从表
df_main = pd.read_csv("/Users/maming/Downloads/test/dataframe_4_join_main.txt",sep='\t',nrows = 100,encoding = "utf-8",engine="python")
print df_main
print "-------"
df_city = pd.read_csv("/Users/maming/Downloads/test/dataframe_4_join_city.txt",sep='\t',nrows = 100,encoding = "utf-8",engine="python")
print df_city

          dt  id   类型  销售额  销售量
0   20190901   1   直营  100   50
1   20190901   1  代理商  200  100
2   20190901   2   直营  300  150
3   20190901   2  代理商  400  200
4   20190902   1   直营  110   51
5   20190902   1  代理商  210  101
6   20190902   2   直营  310  151
7   20190902   2  代理商  410  201
8   20190901   3   直营  500  350
9   20190901   3  代理商  600  500
10  20190901   4   直营  700  450
11  20190901   4  代理商  800  500
12  20190902   3   直营  501  351
13  20190902   3  代理商  601  401
14  20190902   4   直营  701  451
15  20190902   4  代理商  801  501
16  20190902  40  代理商  801  501
-------
   id    市    省  类型
0   1  哈尔滨  黑龙江  直营
1   2   大庆  黑龙江  直营
2   3   邯郸   河北  直营
3   4   涿州   河北  直营
4   5   沧州   河北  直营

In [4]:
### 如果有相同的id,因此会省略on,但是最好还是要写on
print pd.merge(df_main,df_city,on = "id") ### print pd.merge(df_main,df_city)
## 注意 两个表都有相同的字段的时候,展示内容是类型_x 类型_y
print pd.merge(df_main,df_city,on = "id",suffixes = ["_L","_R"]) ### 更改成left 和 right

          dt  id 类型_x  销售额  销售量    市    省 类型_y
0   20190901   1   直营  100   50  哈尔滨  黑龙江   直营
1   20190901   1  代理商  200  100  哈尔滨  黑龙江   直营
2   20190902   1   直营  110   51  哈尔滨  黑龙江   直营
3   20190902   1  代理商  210  101  哈尔滨  黑龙江   直营
4   20190901   2   直营  300  150   大庆  黑龙江   直营
5   20190901   2  代理商  400  200   大庆  黑龙江   直营
6   20190902   2   直营  310  151   大庆  黑龙江   直营
7   20190902   2  代理商  410  201   大庆  黑龙江   直营
8   20190901   3   直营  500  350   邯郸   河北   直营
9   20190901   3  代理商  600  500   邯郸   河北   直营
10  20190902   3   直营  501  351   邯郸   河北   直营
11  20190902   3  代理商  601  401   邯郸   河北   直营
12  20190901   4   直营  700  450   涿州   河北   直营
13  20190901   4  代理商  800  500   涿州   河北   直营
14  20190902   4   直营  701  451   涿州   河北   直营
15  20190902   4  代理商  801  501   涿州   河北   直营
          dt  id 类型_L  销售额  销售量    市    省 类型_R
0   20190901   1   直营  100   50  哈尔滨  黑龙江   直营
1   20190901   1  代理商  200  100  哈尔滨  黑龙江   直营
2   20190902   1   直营  110   51  哈尔滨  黑龙江   直营
3   20190902   1  代理商  210  101  哈尔滨  黑龙江   直营
4   20190901   2   直营  300  150   大庆  黑龙江   直营
5   20190901   2  代理商  400  200   大庆  黑龙江   直营
6   20190902   2   直营  310  151   大庆  黑龙江   直营
7   20190902   2  代理商  410  201   大庆  黑龙江   直营
8   20190901   3   直营  500  350   邯郸   河北   直营
9   20190901   3  代理商  600  500   邯郸   河北   直营
10  20190902   3   直营  501  351   邯郸   河北   直营
11  20190902   3  代理商  601  401   邯郸   河北   直营
12  20190901   4   直营  700  450   涿州   河北   直营
13  20190901   4  代理商  800  500   涿州   河北   直营
14  20190902   4   直营  701  451   涿州   河北   直营
15  20190902   4  代理商  801  501   涿州   河北   直营

In [5]:
### 多字段关联
pd.merge(df_main,df_city,on = ["id",u"类型"])

         dt  id  类型  销售额  销售量    市    省
0  20190901   1  直营  100   50  哈尔滨  黑龙江
1  20190902   1  直营  110   51  哈尔滨  黑龙江
2  20190901   2  直营  300  150   大庆  黑龙江
3  20190902   2  直营  310  151   大庆  黑龙江
4  20190901   3  直营  500  350   邯郸   河北
5  20190902   3  直营  501  351   邯郸   河北
6  20190901   4  直营  700  450   涿州   河北
7  20190902   4  直营  701  451   涿州   河北

In [6]:
## 如果两个表字段不一致时
## left_on  right_on 添加左边和右边表的主键。
## left_index = True/false  right_index = True/false 添加左边和右边表的索引主键
##pd.merge(df_main,df_city,left_on = ["id",u"类型"],right_on = ["id1",u"类型"])

In [7]:
### 连接方式 
### 默认merge是inner join 操作,所以本来数据源有16条数据,最后只显示15条,因为最后一条没有关联上,则不显示
### how = left right outer
print pd.merge(df_main,df_city,on = "id",how = "outer",suffixes = ["_L","_R"]) ### 更改成left 和 right

            dt  id 类型_L    销售额    销售量    市    省 类型_R
0   20190901.0   1   直营  100.0   50.0  哈尔滨  黑龙江   直营
1   20190901.0   1  代理商  200.0  100.0  哈尔滨  黑龙江   直营
2   20190902.0   1   直营  110.0   51.0  哈尔滨  黑龙江   直营
3   20190902.0   1  代理商  210.0  101.0  哈尔滨  黑龙江   直营
4   20190901.0   2   直营  300.0  150.0   大庆  黑龙江   直营
5   20190901.0   2  代理商  400.0  200.0   大庆  黑龙江   直营
6   20190902.0   2   直营  310.0  151.0   大庆  黑龙江   直营
7   20190902.0   2  代理商  410.0  201.0   大庆  黑龙江   直营
8   20190901.0   3   直营  500.0  350.0   邯郸   河北   直营
9   20190901.0   3  代理商  600.0  500.0   邯郸   河北   直营
10  20190902.0   3   直营  501.0  351.0   邯郸   河北   直营
11  20190902.0   3  代理商  601.0  401.0   邯郸   河北   直营
12  20190901.0   4   直营  700.0  450.0   涿州   河北   直营
13  20190901.0   4  代理商  800.0  500.0   涿州   河北   直营
14  20190902.0   4   直营  701.0  451.0   涿州   河北   直营
15  20190902.0   4  代理商  801.0  501.0   涿州   河北   直营
16  20190902.0  40  代理商  801.0  501.0  NaN  NaN  NaN
17         NaN   5  NaN    NaN    NaN   沧州   河北   直营

In [8]:
### 纵向 union all 关联
### 要求两个表的列数相同、类型相同
pd.concat([df_main,df_main])

          dt  id   类型  销售额  销售量
0   20190901   1   直营  100   50
1   20190901   1  代理商  200  100
2   20190901   2   直营  300  150
3   20190901   2  代理商  400  200
4   20190902   1   直营  110   51
5   20190902   1  代理商  210  101
6   20190902   2   直营  310  151
7   20190902   2  代理商  410  201
8   20190901   3   直营  500  350
9   20190901   3  代理商  600  500
10  20190901   4   直营  700  450
11  20190901   4  代理商  800  500
12  20190902   3   直营  501  351
13  20190902   3  代理商  601  401
14  20190902   4   直营  701  451
15  20190902   4  代理商  801  501
16  20190902  40  代理商  801  501
0   20190901   1   直营  100   50
1   20190901   1  代理商  200  100
2   20190901   2   直营  300  150
3   20190901   2  代理商  400  200
4   20190902   1   直营  110   51
5   20190902   1  代理商  210  101
6   20190902   2   直营  310  151
7   20190902   2  代理商  410  201
8   20190901   3   直营  500  350
9   20190901   3  代理商  600  500
10  20190901   4   直营  700  450
11  20190901   4  代理商  800  500
12  20190902   3   直营  501  351
13  20190902   3  代理商  601  401
14  20190902   4   直营  701  451
15  20190902   4  代理商  801  501
16  20190902  40  代理商  801  501

In [9]:
### 上面的demo,索引是重复的,因为默认join的时候是保留了原表的索引的
pd.concat([df_main,df_main],ignore_index = True)

          dt  id   类型  销售额  销售量
0   20190901   1   直营  100   50
1   20190901   1  代理商  200  100
2   20190901   2   直营  300  150
3   20190901   2  代理商  400  200
4   20190902   1   直营  110   51
5   20190902   1  代理商  210  101
6   20190902   2   直营  310  151
7   20190902   2  代理商  410  201
8   20190901   3   直营  500  350
9   20190901   3  代理商  600  500
10  20190901   4   直营  700  450
11  20190901   4  代理商  800  500
12  20190902   3   直营  501  351
13  20190902   3  代理商  601  401
14  20190902   4   直营  701  451
15  20190902   4  代理商  801  501
16  20190902  40  代理商  801  501
17  20190901   1   直营  100   50
18  20190901   1  代理商  200  100
19  20190901   2   直营  300  150
20  20190901   2  代理商  400  200
21  20190902   1   直营  110   51
22  20190902   1  代理商  210  101
23  20190902   2   直营  310  151
24  20190902   2  代理商  410  201
25  20190901   3   直营  500  350
26  20190901   3  代理商  600  500
27  20190901   4   直营  700  450
28  20190901   4  代理商  800  500
29  20190902   3   直营  501  351
30  20190902   3  代理商  601  401
31  20190902   4   直营  701  451
32  20190902   4  代理商  801  501
33  20190902  40  代理商  801  501

In [10]:
### 去掉重复数据
### 因为返回值是DataFrame,因此使用DataFrame的数据处理就可以删除重复数
print type (pd.concat([df_main,df_main],ignore_index = True)) 
pd.concat([df_main,df_main],ignore_index = True).drop_duplicates()

<class 'pandas.core.frame.DataFrame'>

          dt  id   类型  销售额  销售量
0   20190901   1   直营  100   50
1   20190901   1  代理商  200  100
2   20190901   2   直营  300  150
3   20190901   2  代理商  400  200
4   20190902   1   直营  110   51
5   20190902   1  代理商  210  101
6   20190902   2   直营  310  151
7   20190902   2  代理商  410  201
8   20190901   3   直营  500  350
9   20190901   3  代理商  600  500
10  20190901   4   直营  700  450
11  20190901   4  代理商  800  500
12  20190902   3   直营  501  351
13  20190902   3  代理商  601  401
14  20190902   4   直营  701  451
15  20190902   4  代理商  801  501
16  20190902  40  代理商  801  501